jasypt:
  encryptor:
    password: arkhyterima

management:
  endpoints:
    web:
      exposure:
        include: logfile, httptrace, auditevents, loggers, env, mappings, threaddump, metrics, info, routes

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
zuul:
  routes:
    blog:
      stripPrefix: true
      sensitiveHeaders:
    finance:
      stripPrefix: true
      sensitiveHeaders:
    authentication:
      stripPrefix: true
      sensitiveHeaders:
    gateway:
      stripPrefix: true
      sensitiveHeaders:
    approval:
      stripPrefix: true
      sensitiveHeaders:

  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
